import { TAG_META } from "@/lib/theme";
import { isImageIcon } from "@/lib/icon";
import type { ProfileDTO } from "@/lib/profile";

/**
 * Generate the machine-readable `llm.txt` for a profile — a structured,
 * plain-text context file any AI agent can consume. This is logr's moat:
 * a portfolio that an LLM can read and answer questions about directly.
 *
 * Image URLs (avatar, per-highlight photos, image logos) are included and
 * made absolute, so a (multimodal) agent can reference or fetch them.
 */
export function generateLlmTxt(profile: ProfileDTO, origin: string): string {
  const url = `${origin}/${profile.username}`;
  const abs = (u: string) => (/^https?:\/\//.test(u) ? u : `${origin}${u}`);
  const lines: string[] = [];

  lines.push(`# ${profile.name}`);
  lines.push("");
  lines.push(`> ${profile.bio.replace(/\n/g, " ")}`);
  lines.push("");

  lines.push("## Profile");
  lines.push(`- Name: ${profile.name}`);
  lines.push(`- Handle: ${profile.handle}`);
  if (profile.status) lines.push(`- Currently: ${profile.status}`);
  if (profile.location) lines.push(`- Location: ${profile.location}`);
  lines.push(`- Portfolio: ${url}`);
  if (profile.avatarUrl) lines.push(`- Avatar: ${abs(profile.avatarUrl)}`);
  for (const s of profile.socials) lines.push(`- ${s.label}: ${s.href}`);
  lines.push("");

  if (profile.about) {
    lines.push("## About");
    lines.push(profile.about.trim());
    lines.push("");
  }

  lines.push("## Timeline");
  lines.push(
    "A reverse-chronological record of work, milestones, talks, side quests, and writing."
  );
  lines.push("");

  for (const h of profile.highlights) {
    const tagLabel = TAG_META[h.tag]?.label ?? h.tag;
    lines.push(`### ${h.title}`);
    lines.push(`- Date: ${h.date}`);
    lines.push(`- Type: ${tagLabel}`);
    lines.push(`- Details: ${h.body.replace(/\n/g, " ")}`);
    if (h.link) lines.push(`- Link: ${h.link.label} (${h.link.href})`);
    if (isImageIcon(h.icon)) lines.push(`- Logo: ${abs(h.icon)}`);
    if (h.images.length) lines.push(`- Photos: ${h.images.map(abs).join(", ")}`);
    lines.push("");
  }

  lines.push("---");
  lines.push(
    `Generated by logr (${origin}). This file is a structured context layer for AI tools.`
  );

  return lines.join("\n");
}
